### ISSUE TITLE
Github repositories available for a user not showing in Codeology search.

### ISSUE THREAD

**Issue by zgannon** [project-codeology/codeology#6]
Codeology never updates my public Github repositories to view on the website, as shown below:
![codeology_error](https://cloud.githubusercontent.com/assets/7028393/23260224/c7b35b1c-f99e-11e6-9b4a-a518fa88f7a5.PNG)

But I have 2 public repos currently. This has always been an issue since discovering Codeology a year and a half or so ago. It's a cool concept and would like to see more of my code visualized.

**Comment by marpi** [comment]
We just cleared the cache, you can see both of you repositories now:
http://codeology.braintreepayments.com/Gannon93
